const calculateDiscountedPrice = (price, discount) => {
  return +(price - (price * discount) / 100).toFixed(2);
};
const featuredProducts = [
  {
    id: "prod-t1",
    name: "Premium Leather Crossbody Bag",
    brand: "Luxemart",
    category: "trending",
    description:
      "Handcrafted from premium full-grain leather, this crossbody bag combines elegance with practicality. Features multiple compartments and an adjustable strap.",
    price: 189.99,
    discount: 15,
    discountedPrice: 161.49,
    rating: 4.8,
    reviewCount: 124,
    isNew: false,
    images: [
      "https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    colors: ["Black", "Brown", "Tan"],
    stock: 45,
    features: [
      "Full-grain leather construction",
      "Multiple interior compartments",
      "Adjustable shoulder strap",
      "Brass hardware",
      "Interior zip pocket",
    ],
  },
  {
    id: "prod-t2",
    name: "Wireless Noise-Cancelling Headphones",
    brand: "SoundPeak",
    category: "electronics",
    description:
      "Immerse yourself in music with these wireless headphones featuring active noise cancellation and 20-hour battery life.",
    price: 249.99,
    discount: 10,
    discountedPrice: 224.99,
    rating: 4.7,
    reviewCount: 89,
    isNew: true,
    images: [
      "https://images.pexels.com/photos/577769/pexels-photo-577769.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    colors: ["Black", "Silver", "Blue"],
    stock: 60,
    features: [
      "Active noise cancellation",
      "20-hour battery life",
      "Bluetooth 5.0",
      "Foldable design",
      "Built-in microphone",
    ],
  },
  {
    id: "prod-t3",
    name: "Smart Fitness Tracker",
    brand: "FitPulse",
    category: "wearables",
    description:
      "Track your fitness goals with this sleek smartwatch, featuring heart rate monitoring, sleep tracking, and water resistance.",
    price: 79.99,
    discount: 20,
    discountedPrice: 63.99,
    rating: 4.5,
    reviewCount: 210,
    isNew: false,
    images: [
      "https://images.pexels.com/photos/437038/pexels-photo-437038.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    colors: ["Black", "Red", "White"],
    stock: 120,
    features: [
      "Heart rate monitor",
      "Sleep tracking",
      "Water-resistant up to 50m",
      "Step counter",
      "Smart notifications",
    ],
  },
  {
    id: "prod-t4",
    name: "Stainless Steel Water Bottle",
    brand: "EcoWave",
    category: "outdoor",
    description:
      "Keep your drinks hot or cold for up to 24 hours with this double-walled stainless steel water bottle.",
    price: 34.99,
    discount: 5,
    discountedPrice: 33.24,
    rating: 4.9,
    reviewCount: 305,
    isNew: true,
    images: [
      "https://images.pexels.com/photos/1289363/pexels-photo-1289363.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    colors: ["Silver", "Black", "Green"],
    stock: 200,
    features: [
      "Double-walled insulation",
      "Leak-proof cap",
      "BPA-free",
      "24-hour temperature retention",
      "Lightweight design",
    ],
  },
  {
    id: "prod-t5",
    name: "Vintage Polarized Sunglasses",
    brand: "SunVibe",
    category: "accessories",
    description:
      "Classic style meets modern protection with these polarized sunglasses, offering UV400 protection and a retro look.",
    price: 59.99,
    discount: 25,
    discountedPrice: 44.99,
    rating: 4.6,
    reviewCount: 150,
    isNew: false,
    images: [
      "https://images.pexels.com/photos/46710/pexels-photo-46710.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    colors: ["Black", "Tortoise", "Gold"],
    stock: 80,
    features: [
      "Polarized lenses",
      "UV400 protection",
      "Lightweight frame",
      "Anti-slip nose pads",
      "Durable hinges",
    ],
  },
  {
    id: "prod-t6",
    name: "Portable Espresso Maker",
    brand: "BrewGo",
    category: "kitchen",
    description:
      "Enjoy barista-quality espresso on the go with this compact, battery-powered espresso maker.",
    price: 99.99,
    discount: 10,
    discountedPrice: 89.99,
    rating: 4.4,
    reviewCount: 67,
    isNew: true,
    images: [
      "https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    colors: ["Black", "Silver"],
    stock: 50,
    features: [
      "Battery-powered",
      "Compact design",
      "15-bar pressure",
      "Compatible with capsules",
      "Easy to clean",
    ],
  },
  {
    id: "prod-t7",
    name: "Ceramic Nonstick Cookware Set",
    brand: "CookEase",
    category: "kitchen",
    description:
      "This 5-piece ceramic cookware set offers nonstick performance and even heat distribution for effortless cooking.",
    price: 149.99,
    discount: 20,
    discountedPrice: 119.99,
    rating: 4.7,
    reviewCount: 98,
    isNew: false,
    images: [
      "https://images.pexels.com/photos/264636/pexels-photo-264636.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    colors: ["Black", "Blue", "Red"],
    stock: 30,
    features: [
      "Ceramic nonstick coating",
      "Oven-safe up to 400°F",
      "Ergonomic handles",
      "Even heat distribution",
      "Dishwasher safe",
    ],
  },
  {
    id: "prod-t8",
    name: "Smart LED Desk Lamp",
    brand: "BrightLife",
    category: "home",
    description:
      "Adjustable brightness and color temperature make this smart LED desk lamp perfect for work or relaxation.",
    price: 69.99,
    discount: 15,
    discountedPrice: 59.49,
    rating: 4.5,
    reviewCount: 112,
    isNew: true,
    images: [
      "https://images.pexels.com/photos/1112598/pexels-photo-1112598.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    colors: ["White", "Black", "Silver"],
    stock: 75,
    features: [
      "Adjustable brightness",
      "Color temperature control",
      "USB charging port",
      "Touch controls",
      "Energy-efficient LEDs",
    ],
  },
  {
    id: "prod-t9",
    name: "Foldable Travel Backpack",
    brand: "TrekMate",
    category: "travel",
    description:
      "This lightweight, foldable backpack is perfect for travel, with water-resistant fabric and multiple compartments.",
    price: 44.99,
    discount: 10,
    discountedPrice: 40.49,
    rating: 4.3,
    reviewCount: 88,
    isNew: false,
    images: [
      "https://images.pexels.com/photos/373125/pexels-photo-373125.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    colors: ["Navy", "Gray", "Green"],
    stock: 100,
    features: [
      "Water-resistant material",
      "Foldable design",
      "Laptop compartment",
      "Breathable straps",
      "Side pockets",
    ],
  },
  {
    id: "prod-t10",
    name: "Wireless Charging Pad",
    brand: "ChargeFast",
    category: "electronics",
    description:
      "Fast and efficient, this wireless charging pad supports multiple devices with a sleek, minimalist design.",
    price: 29.99,
    discount: 5,
    discountedPrice: 28.49,
    rating: 4.6,
    reviewCount: 145,
    isNew: true,
    images: [
      "https://images.pexels.com/photos/5082566/pexels-photo-5082566.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    colors: ["Black", "White"],
    stock: 90,
    features: [
      "Fast charging",
      "Qi-compatible",
      "Non-slip surface",
      "Overheat protection",
      "Compact design",
    ],
  },
  {
    id: "prod-t11",
    name: "Luxury Cashmere Scarf",
    brand: "SoftTouch",
    category: "accessories",
    description:
      "Wrap yourself in elegance with this 100% cashmere scarf, perfect for any season.",
    price: 89.99,
    discount: 20,
    discountedPrice: 71.99,
    rating: 4.8,
    reviewCount: 76,
    isNew: false,
    images: [
      "https://images.pexels.com/photos/375880/pexels-photo-375880.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    colors: ["Gray", "Navy", "Cream"],
    stock: 40,
    features: [
      "100% cashmere",
      "Soft and lightweight",
      "Versatile design",
      "Warm and breathable",
      "Hand-washable",
    ],
  },
  {
    id: "prod-t12",
    name: "Smart Home Security Camera",
    brand: "SafeGuard",
    category: "electronics",
    description:
      "Monitor your home with this HD security camera featuring night vision and motion detection.",
    price: 129.99,
    discount: 15,
    discountedPrice: 110.49,
    rating: 4.4,
    reviewCount: 102,
    isNew: true,
    images: [
      "https://images.pexels.com/photos/104827/cat-pet-animal-domestic-104827.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    colors: ["White", "Black"],
    stock: 55,
    features: [
      "1080p HD video",
      "Night vision",
      "Motion detection",
      "Two-way audio",
      "Cloud storage option",
    ],
  },
  {
    id: "prod-t13",
    name: "Bamboo Cutting Board Set",
    brand: "EcoChef",
    category: "kitchen",
    description:
      "This set of three bamboo cutting boards is perfect for all your prep needs, with a durable and eco-friendly design.",
    price: 39.99,
    discount: 10,
    discountedPrice: 35.99,
    rating: 4.7,
    reviewCount: 130,
    isNew: false,
    images: [
      "https://images.pexels.com/photos/2797506/pexels-photo-2797506.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    colors: ["Natural"],
    stock: 85,
    features: [
      "100% bamboo",
      "Three sizes",
      "Knife-friendly surface",
      "Easy to clean",
      "Eco-friendly",
    ],
  },
  {
    id: "prod-t14",
    name: "Running Shoes",
    brand: "SpeedPulse",
    category: "footwear",
    description:
      "Lightweight and breathable, these running shoes provide excellent support and cushioning for your daily runs.",
    price: 99.99,
    discount: 20,
    discountedPrice: 79.99,
    rating: 4.5,
    reviewCount: 165,
    isNew: true,
    images: [
      "https://images.pexels.com/photos/2529147/pexels-photo-2529147.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    colors: ["Black", "White", "Blue"],
    stock: 70,
    features: [
      "Breathable mesh upper",
      "Cushioned sole",
      "Lightweight design",
      "Non-slip outsole",
      "Arch support",
    ],
  },
  {
    id: "prod-t15",
    name: "Portable Power Bank",
    brand: "ChargePro",
    category: "electronics",
    description:
      "Stay powered up with this 10000mAh power bank, featuring fast charging and a compact design.",
    price: 49.99,
    discount: 10,
    discountedPrice: 44.99,
    rating: 4.6,
    reviewCount: 190,
    isNew: false,
    images: [
      "https://images.pexels.com/photos/1632790/pexels-photo-1632790.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    colors: ["Black", "Silver", "Red"],
    stock: 110,
    features: [
      "10000mAh capacity",
      "Fast charging",
      "Dual USB ports",
      "LED indicator",
      "Compact design",
    ],
  },
  {
    id: "prod-t16",
    name: "Minimalist Wall Clock",
    brand: "TimeCraft",
    category: "home",
    description:
      "Add a touch of modern elegance to your space with this silent, minimalist wall clock.",
    price: 59.99,
    discount: 15,
    discountedPrice: 50.99,
    rating: 4.8,
    reviewCount: 95,
    isNew: true,
    images: [
      "https://images.pexels.com/photos/2783873/pexels-photo-2783873.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    colors: ["Black", "White", "Wood"],
    stock: 65,
    features: [
      "Silent quartz movement",
      "Minimalist design",
      "Easy to read",
      "Battery-operated",
      "Lightweight",
    ],
  },
  {
    id: "prod-t17",
    name: "Yoga Mat",
    brand: "ZenFit",
    category: "fitness",
    description:
      "This eco-friendly yoga mat offers superior grip and cushioning for your practice.",
    price: 34.99,
    discount: 10,
    discountedPrice: 31.49,
    rating: 4.7,
    reviewCount: 140,
    isNew: false,
    images: [
      "https://images.pexels.com/photos/3823039/pexels-photo-3823039.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    colors: ["Blue", "Purple", "Green"],
    stock: 90,
    features: [
      "Eco-friendly material",
      "Non-slip surface",
      "6mm thickness",
      "Lightweight",
      "Carrying strap included",
    ],
  },
  {
    id: "prod-t18",
    name: "Stainless Steel Travel Mug",
    brand: "ThermaCup",
    category: "outdoor",
    description:
      "Keep your coffee hot for hours with this insulated stainless steel travel mug.",
    price: 24.99,
    discount: 5,
    discountedPrice: 23.74,
    rating: 4.9,
    reviewCount: 220,
    isNew: true,
    images: [
      "https://images.pexels.com/photos/1289363/pexels-photo-1289363.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    colors: ["Silver", "Black", "Blue"],
    stock: 150,
    features: [
      "Double-walled insulation",
      "Leak-proof lid",
      "BPA-free",
      "Fits most cupholders",
      "12-hour heat retention",
    ],
  },
  {
    id: "prod-t19",
    name: "Electric Kettle",
    brand: "QuickBoil",
    category: "kitchen",
    description:
      "Boil water in minutes with this sleek electric kettle, featuring auto shut-off and a 1.7L capacity.",
    price: 49.99,
    discount: 15,
    discountedPrice: 42.49,
    rating: 4.6,
    reviewCount: 115,
    isNew: false,
    images: [
      "https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    colors: ["Silver", "Black"],
    stock: 70,
    features: [
      "1.7L capacity",
      "Auto shut-off",
      "Stainless steel body",
      "Boil-dry protection",
      "Cordless design",
    ],
  },
  {
    id: "prod-t20",
    name: "Leather Journal",
    brand: "WriteWell",
    category: "stationery",
    description:
      "Capture your thoughts in this handcrafted leather journal with premium acid-free paper.",
    price: 39.99,
    discount: 10,
    discountedPrice: 35.99,
    rating: 4.8,
    reviewCount: 80,
    isNew: true,
    images: [
      "https://images.pexels.com/photos/159666/pexels-photo-159666.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    colors: ["Brown", "Black"],
    stock: 60,
    features: [
      "Genuine leather cover",
      "Acid-free paper",
      "Bookmark ribbon",
      "Elastic closure",
      "192 pages",
    ],
  },
];

module.exports = featuredProducts;
